Hanbell-KPI/src/java/cn/hanbell/kpi/control/ProductSetManagedBean.java
Hanbell-KPI/web/app/prod/productsetEdit.xhtml
Hanbell-KPI/web/app/prod/productsetView.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/entity/Indicator.java
KPI-ejb/src/java/cn/hanbell/kpi/entity/IndicatorAssignment.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountT9.java

增加产品指标冻结日期，避免覆盖历史正确数字

---

Hanbell-KPI/src/java/cn/hanbell/kpi/control/ProductSetManagedBean.java
Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/ShipmentTopManagedBean.java
Hanbell-KPI/web/app/bsc/clientranking.xhtml
Hanbell-KPI/web/app/prod/productsetEdit.xhtml
Hanbell-KPI/web/app/prod/productsetView.xhtml
Hanbell-KPI/web/empty.xhtml
Hanbell-KPI/web/error.xhtml
Hanbell-KPI/web/sys/indicatorchart.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/ejb/IndicatorBean.java
KPI-ejb/src/java/cn/hanbell/kpi/entity/Indicator.java
KPI-ejb/src/java/cn/hanbell/kpi/entity/IndicatorAssignment.java

增加辅助数据维护功能

---

Hanbell-KPI/web/app/bsc/shipmentchart.xhtml
Hanbell-KPI/web/app/bsc/shipmentsheet.xhtml
Hanbell-KPI/web/app/prod/productset.xhtml
Hanbell-KPI/web/resources/css/master.css
KPI-ejb/src/java/cn/hanbell/kpi/ejb/IndicatorBean.java
KPI-ejb/src/java/cn/hanbell/kpi/entity/Indicator.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutter.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutterFX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutterFXo2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutterFXo3.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutterYX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutterYXo2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ConsumptionCutterYXo3.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessQuantity.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessQuantityHFX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessQuantityHFXandYX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessQuantityHYX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessRatio.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessRatioFX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessRatioFXO1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessRatioYX.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessRatioYXO1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessScrapQuantity.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProcessScrapRatioQ.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/Production.java
KPI-ejb/src/java/cn/hanbell/kpi/mail/WXShipmentMailBean.java

报表CSS调整,计算值保留小数位

---

KPI-ejb/src/java/cn/hanbell/kpi/mail/SHBShipmentMailBean.java

SHB每日出货增加VHB数据

---

Hanbell-KPI/src/java/cn/hanbell/kpi/web/BscChartManagedBean.java
Hanbell-KPI/src/java/cn/hanbell/kpi/web/BscSheetManagedBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceERP.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceOuter5AB.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceWithin5AB.java

柯茂免费服务条件修改

---

Hanbell-KPI/web/app/bsc/qraqualifiedfx.xhtml
Hanbell-KPI/web/app/bsc/qraqualifiedyx.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderAmountR1B1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderAmountR1B2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderAmountR1B3.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityR1B1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityR1B2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityR1B3.java

R冷媒华东订单逻辑调整

---

Hanbell-KPI/src/java/cn/hanbell/kpi/timer/TimerBean.java
KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupHSShipmentBean.java
KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupServiceBean.java
KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupShipmentBean.java
KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupVHServiceBean.java
KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupVHShipmentBean.java
KPI-ejb/src/java/cn/hanbell/kpi/mail/GroupShipmentMailBean.java

集团报表 越南和汉声部分

---

KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupShipmentBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/Shipment.java

SHB与集团报表逻辑修改

---

Hanbell-KPI/src/java/cn/hanbell/kpi/control/UserManagedBean.java

未按基准日期设置菜单Bug修正

---

KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupServiceBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityAA2TW.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmount9.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountAA9.java

修改A机组收费服务金额

---

Hanbell-KPI/src/java/cn/hanbell/kpi/timer/TimerBean.java

下一版本使用PrimeFaces6.2和Ultima1.1.5

TimerBean代码冲突修正

---

Hanbell-KPI/src/java/cn/hanbell/kpi/timer/TimerBean.java
KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupHSShipmentBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/QRACubicElementAmountBad.java

修改 品保三次元逻辑 集团报表汉声出货逻辑 包含系统更新排程的时间

修改 品保三次元逻辑 集团报表汉声出货逻辑

---

KPI-ejb/src/java/cn/hanbell/erp/ejb/BscGroupHSShipmentBean.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmts.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsHT.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsHTV1.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsHTV2.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsHTV3.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsOTH.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsOTHV1.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsOTHV2.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsOTHV3.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsQT.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsQTV1.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsQTV2.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmtsQTV3.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTon.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonHT.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonHTV1.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonHTV2.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonHTV3.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonOTH.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonOTHV1.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonOTHV2.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonOTHV3.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonQT.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonQTV1.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonQTV2.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentTonQTV3.java

汉声出货报表逻辑调整

---

KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProductionPlanOrder.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ProductionPlanOrderKM.java

增加固定条件 and d.n_code_DD <> 'ZZ'

每日生产状况表订单统计逻辑修改

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/ComplaintsChartReportActBean.java
Hanbell-KPI/web/app/bsc/complaintschart.xhtml
Hanbell-KPI/web/app/bsc/complaintschartajz.xhtml
Hanbell-KPI/web/app/bsc/complaintschartb.xhtml
Hanbell-KPI/web/app/bsc/complaintschartc.xhtml
Hanbell-KPI/web/app/bsc/complaintschartp.xhtml
Hanbell-KPI/web/app/bsc/complaintschartpzk.xhtml
Hanbell-KPI/web/app/bsc/inventoryamount.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/QRAComplaintActualAA1V2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/QRAComplaintActualAH1V2.java

品保BSC 格式 代码修改

---

KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/GroupServiceBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/GroupVHServiceBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/GroupVHShipmentBean.java

集团报表越南代码优化

---

KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/GroupVHServiceBean.java

越南排程失败 代码修改

---

KPI-ejb/src/conf/persistence.xml
KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/GroupVHShipmentBean.java

集团报表-越南自动排程异常问题处理

---

KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentAmts.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/ShipmentDelyAmts.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/VarietyAmts.java

汉声出货报表逻辑修改

---

Hanbell-KPI/src/java/cn/hanbell/kpi/control/InventoryProductManagedBean.java
Hanbell-KPI/web/app/bsc/inventoryamountsheet.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/ejb/InventoryIndicatorBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4E71.java

财务库存报表 代码修改

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/InventoryReportBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA2C50.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA2C51.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA2C53.java
KPI-ejb/src/java/cn/hanbell/kpi/mail/InventoryIndicatorMailBean.java

新增 财务库存达标情况表自动派送

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/ComplaintsChartReportBean.java
Hanbell-KPI/web/app/bsc/complaintschart.xhtml
Hanbell-KPI/web/app/bsc/inventorydepartmentsheet.xhtml
Hanbell-KPI/web/app/bsc/inventoryindicatorsheet.xhtml
Hanbell-KPI/web/app/bsc/inventoryproductsheet.xhtml
Hanbell-KPI/web/resources/css/master.css

财务库存报表格式修改 品保客诉格式修改

---

Hanbell-KPI/web/app/bsc/inventorydepartmentsheet.xhtml
Hanbell-KPI/web/app/bsc/inventoryindicatorsheet.xhtml
Hanbell-KPI/web/app/bsc/inventoryproductsheet.xhtml

财务库存报表 格式调整

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/ShipmentAmountSheetReportBean.java
Hanbell-KPI/web/WEB-INF/faces-config.xml
Hanbell-KPI/web/app/bsc/clientranking.xhtml
Hanbell-KPI/web/app/bsc/shipmentamountsheet.xhtml

1、客户排名同比差异负值颜色变更
2、RAPS金额汇总表增加营业小计、收费服务小计

经营汇报提出问题修改

---

Hanbell-KPI/src/java/cn/hanbell/kpi/control/IndicatorCloneManagedBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/IndicatorBean.java
KPI-ejb/src/java/cn/hanbell/kpi/entity/Indicator.java

指标Clone功能优化

---

KPI-ejb/src/java/cn/hanbell/kpi/ejb/InventoryDepartmentBean.java

财务库存报表异常处理

---

KPI-ejb/src/java/cn/hanbell/kpi/mail/GroupShipmentMailBean.java

集团报表上传台湾同步更新

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/TurnoverdaysBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/InventoryTurnoverBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/BscGroupVHSaleOrderBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/erp/BscGroupVHShipmentBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1AAm.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1AAy.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1AHm.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1AHy.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1B05m.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1B05y.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1B30m.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1B30y.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1B40m.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1B40y.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1Pm.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1Py.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1Rm.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1Ry.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1Sm.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryTurnoverA1Sy.java

库存周转天数逻辑修改

---

KPI-ejb/src/java/cn/hanbell/kpi/mail/AAEmployeeMailBean.java

机组销售业绩汇总表修改

---

KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainQuantity.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainQuantityAH.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainQuantityP.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainQuantityR.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainTime.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainTimeP.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ServiceMaintainTimeR.java

服务维修数据统计表逻辑修改

---

Hanbell-KPI/web/app/bsc/complaintschartajz.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/comm/BscProductiontMail.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA3KOH.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KBA.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KHC.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KHE.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KHG.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KHM.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KHT.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KRT.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KWC.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/InventoryAmountA4KWL.java

生产计划表修改和财务报表和品保BSC修改

---

Hanbell-KPI/web/app/perf/scorecardsetView.xhtml

绩效考核指标查看页面修改

---

Hanbell-KPI/web/sys/indicatorfreeze.xhtml

这个DOCTYPE必须写

---

KPI-ejb/src/java/cn/hanbell/kpi/mail/RSalesOrderMailBean.java
KPI-ejb/src/java/cn/hanbell/kpi/mail/RShipmentMailBean.java

R冷媒每日报表格式修改

---

KPI-ejb/src/java/cn/hanbell/kpi/mail/RSalesOrderMailBean.java

R冷媒订单报表逻辑修改

---

KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityPPL1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityPPL2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountPPL1.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountPPL2.java

真空订单出货指标逻辑修改

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/ComplaintsChartReportBean.java
Hanbell-KPI/src/java/cn/hanbell/kpi/web/BscChartManagedBean.java
Hanbell-KPI/src/java/cn/hanbell/kpi/web/BscSheetManagedBean.java
Hanbell-KPI/web/app/bsc/castingratehs.xhtml
Hanbell-KPI/web/app/bsc/complaintschart.xhtml
Hanbell-KPI/web/app/bsc/complaintschartajz.xhtml
Hanbell-KPI/web/app/bsc/complaintschartc.xhtml
Hanbell-KPI/web/app/bsc/complaintschartp.xhtml
Hanbell-KPI/web/app/bsc/freeservicechart.xhtml
Hanbell-KPI/web/app/bsc/freeserviceparentsheet.xhtml
Hanbell-KPI/web/app/bsc/freeservicesheet.xhtml
Hanbell-KPI/web/app/bsc/inventoryamount1Nsheet.xhtml
Hanbell-KPI/web/app/bsc/inventoryamountsheet.xhtml
Hanbell-KPI/web/app/bsc/materialsaccproject.xhtml
Hanbell-KPI/web/app/bsc/materialscustcomplaint.xhtml
Hanbell-KPI/web/app/bsc/materialsfreightrate.xhtml
Hanbell-KPI/web/app/bsc/materialsfreightrate1.xhtml
Hanbell-KPI/web/app/bsc/materialspricesheet.xhtml
Hanbell-KPI/web/app/bsc/percentofpass.xhtml
Hanbell-KPI/web/app/bsc/percentofpassjz.xhtml
Hanbell-KPI/web/app/bsc/percentofpassp.xhtml
Hanbell-KPI/web/app/bsc/percentofpassr.xhtml
Hanbell-KPI/web/app/bsc/productionchart.xhtml
Hanbell-KPI/web/app/bsc/productionsheet.xhtml
Hanbell-KPI/web/app/bsc/shipmentamountsheet.xhtml
Hanbell-KPI/web/app/bsc/shipmentchart.xhtml
Hanbell-KPI/web/app/bsc/shipmentsheet.xhtml
Hanbell-KPI/web/app/bsc/turnoverdays.xhtml
Hanbell-KPI/web/app/perf/scorecardsetEdit.xhtml

各单位BSC报表显示格式调整

---

KPI-ejb/src/java/cn/hanbell/kpi/ejb/ProcurementBean.java
KPI-ejb/src/java/cn/hanbell/kpi/mail/RServiceChargeMailBean.java
KPI-ejb/src/java/cn/hanbell/kpi/mail/ServiceChargeMailBean.java

采购表逻辑修改和收费服务发送日期修改

---

KPI-ejb/src/java/cn/hanbell/kpi/evaluation/MaterielFCR.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/MaterielPickingQuantity.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/MaterielReturnQuantity.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderAmountAQT.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/SalesOrderQuantityAQT.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountAQT.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentQuantityAQT.java

Add A机体出货增加其他项（AQT）

---

Hanbell-KPI/src/java/cn/hanbell/kpi/control/ScorecardCloneManagedBean.java
Hanbell-KPI/web/WEB-INF/faces-config.xml
Hanbell-KPI/web/sys/scorecardclone.xhtml
KPI-ejb/src/java/cn/hanbell/kpi/ejb/ScorecardBean.java
KPI-ejb/src/java/cn/hanbell/kpi/entity/Scorecard.java

Add 绩效考核复制功能

---

KPI-ejb/src/java/cn/hanbell/kpi/comm/MailNotify.java

Update 服务器地址 改为172.16.10.108

---

KPI-ejb/src/java/cn/hanbell/kpi/comm/MailNotify.java

This reverts commit db12177eac25ca5496b70b3834a98bc4ff5392a6, reversing
changes made to 97eae726da98ef6f85983b7403fc558ddd8e8463.

Revert "Merge pull request #297 from hanbellgp/HL"

---

Hanbell-KPI/src/java/cn/hanbell/kpi/rpt/FinancingFreeServiceReportBean.java
KPI-ejb/src/java/cn/hanbell/kpi/ejb/InventoryProductBean.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceWithinKS1G.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceWithinKS1H.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceWithinKS1Q.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/FreeServiceWithinKS1U.java

1.免费服务逻辑修改
2.库存金额逻辑修改
3.资金回收率逻辑修改

KPI部分功能逻辑修改

---

KPI-ejb/src/conf/persistence.xml
KPI-ejb/src/java/cn/hanbell/kpi/comm/SuperEJBForMES.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmount.java
KPI-ejb/src/java/cn/hanson/kpi/evaluation/MachiningEfficiency.java

GF需要新增连接配置 jdbc/hansonmes和jdbc/hanyoungmes

增加HS/HY MES DB连接配置

---

KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountKWC2.java
KPI-ejb/src/java/cn/hanbell/kpi/evaluation/ShipmentAmountR1C2.java

1.济南销退时部门新增为济南
2.再生能源螺杆机组出货金额新增后处理

制冷出货和再生出货调整
